// AUTO-GENERATED by scripts/upload-cloudinary-whatsapp-assets.mjs
// Re-run when WhatsApp/testimonial media changes.

export const CLOUDINARY_WHATSAPP_SCREENSHOTS = [
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099383/mentorque/whatsapp-testimonials/screenshots/1.jpg",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099385/mentorque/whatsapp-testimonials/screenshots/1.png",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099386/mentorque/whatsapp-testimonials/screenshots/12.png",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099388/mentorque/whatsapp-testimonials/screenshots/14.png",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099389/mentorque/whatsapp-testimonials/screenshots/16.png",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099390/mentorque/whatsapp-testimonials/screenshots/17.png",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099391/mentorque/whatsapp-testimonials/screenshots/18.jpg",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099393/mentorque/whatsapp-testimonials/screenshots/19.jpg",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099394/mentorque/whatsapp-testimonials/screenshots/2.png",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099395/mentorque/whatsapp-testimonials/screenshots/20.jpg",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099396/mentorque/whatsapp-testimonials/screenshots/3.png",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099397/mentorque/whatsapp-testimonials/screenshots/5.png",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099398/mentorque/whatsapp-testimonials/screenshots/6-5.jpg",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099399/mentorque/whatsapp-testimonials/screenshots/6.jpg",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099400/mentorque/whatsapp-testimonials/screenshots/8.jpg",
  "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099401/mentorque/whatsapp-testimonials/screenshots/imp2.jpg",
] as const;

export const CLOUDINARY_VIDEO_TESTIMONIALS = {
  "testimonial3.mp4": "https://res.cloudinary.com/dyklktxlw/video/upload/v1774099435/mentorque/video-testimonials/videos/testimonial3.mp4",
  "testinomial1.mp4": "https://res.cloudinary.com/dyklktxlw/video/upload/v1774099441/mentorque/video-testimonials/videos/testinomial1.mp4",
  "testinomial2.mp4": "https://res.cloudinary.com/dyklktxlw/video/upload/v1774099443/mentorque/video-testimonials/videos/testinomial2.mp4",
  "testinomial4.mp4": "https://res.cloudinary.com/dyklktxlw/video/upload/v1774099452/mentorque/video-testimonials/videos/testinomial4.mp4",
} as const;

export const CLOUDINARY_VIDEO_THUMBNAILS = {
  "Thumbnail Debmaliya.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099416/mentorque/video-testimonials/thumbnails/thumbnail-debmaliya.png",
  "Thumbnail Morgan.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099417/mentorque/video-testimonials/thumbnails/thumbnail-morgan.png",
  "Thumbnail Snehashish.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099418/mentorque/video-testimonials/thumbnails/thumbnail-snehashish.png",
  "Thumbnail Sreelaxmi.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099420/mentorque/video-testimonials/thumbnails/thumbnail-sreelaxmi.png",
} as const;

export const CLOUDINARY_TEAM_PICS = {
  "Afeef Website.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099403/mentorque/team-pics/afeef-website.png",
  "Anchita Website.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099405/mentorque/team-pics/anchita-website.png",
  "Gokul Website.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099407/mentorque/team-pics/gokul-website.png",
  "Nyai Website.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099409/mentorque/team-pics/nyai-website.png",
  "Palak Website.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099410/mentorque/team-pics/palak-website.png",
  "Raajit Website.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099412/mentorque/team-pics/raajit-website.png",
  "Shikhar Website.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099413/mentorque/team-pics/shikhar-website.png",
  "Shresth Website.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774099415/mentorque/team-pics/shresth-website.png",
} as const;
