// AUTO-GENERATED by scripts/upload-cloudinary-assets.mjs
// Re-run the script when source image files change.

export const CLOUDINARY_INTERVIEW_SUCCESS = {
  laptop: "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097671/mentorque/interview-success/macbook-bg-less.svg",
} as const;

export const CLOUDINARY_CAREERS_HERO = {
  "amazon-stock": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097676/mentorque/careers-hero/amazon-stock.jpg",
  "apple": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097677/mentorque/careers-hero/apple.webp",
  "bangalore": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097679/mentorque/careers-hero/bangalore.jpg",
  "dublin-stock": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097680/mentorque/careers-hero/dublin-stock.jpg",
  "googlehq": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097681/mentorque/careers-hero/googlehq.jpg",
  "london-stock-photo": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097682/mentorque/careers-hero/london-stock-photo.jpg",
  "vodafone-stock-photo": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097683/mentorque/careers-hero/vodafone-stock-photo.jpg",
} as const;

export const CLOUDINARY_MENTORS_BG_REMOVED = {
  "Abhik Mehta.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097684/mentorque/mentors-bg-removed/abhik-mehta.png",
  "Adori.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097685/mentorque/mentors-bg-removed/adori.png",
  "Agniva Dutta.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097687/mentorque/mentors-bg-removed/agniva-dutta.png",
  "Akash Anand.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097688/mentorque/mentors-bg-removed/akash-anand.png",
  "Aryan Chandna.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097689/mentorque/mentors-bg-removed/aryan-chandna.png",
  "Aswini.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097691/mentorque/mentors-bg-removed/aswini.png",
  "Ayush Shankar.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097692/mentorque/mentors-bg-removed/ayush-shankar.png",
  "Gayatri Poddar.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097694/mentorque/mentors-bg-removed/gayatri-poddar.png",
  "Harshal Desai.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097699/mentorque/mentors-bg-removed/harshal-desai.png",
  "Nirvan Kashyap.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097701/mentorque/mentors-bg-removed/nirvan-kashyap.png",
  "Pratibha Gowrishankar.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097702/mentorque/mentors-bg-removed/pratibha-gowrishankar.png",
  "Shayak Das.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097703/mentorque/mentors-bg-removed/shayak-das.png",
  "Shivanjali Verma.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097705/mentorque/mentors-bg-removed/shivanjali-verma.png",
  "Sparsh Prasad.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097706/mentorque/mentors-bg-removed/sparsh-prasad.png",
  "Tripti Kumari.png": "https://res.cloudinary.com/dyklktxlw/image/upload/v1774097709/mentorque/mentors-bg-removed/tripti-kumari.png",
} as const;
